### PR TITLE
installation script for version 1.6

### PR DESCRIPTION
**Pull request by bolajiwahab**
This PR adds an installation script for version 1.6.
The installation script is sourced from https://github.com/adjust/pg-telemetry/blob/master/extension/pgtelemetry-head.sql

Sample error:
```
CREATE EXTENSION pgtelemetry;
ERROR:  extension "pgtelemetry" has no installation script nor update path for version "1.6"
```

### CODE REVIEW

**Comment by za-arthur** [comment]
It isn't really necessary to have full installation script. There is an update script:
https://github.com/adjust/pg-telemetry/blob/master/extension/pgtelemetry--1.5.sql--1.6.sql

**Comment by bolajiwahab** [comment]
> It isn't really necessary to have full installation script. There is an update script: https://github.com/adjust/pg-telemetry/blob/master/extension/pgtelemetry--1.5.sql--1.6.sql

Yes, there is but new installation defaults to 1.6. This means we need an installation script for it. The other way is to install 1.5 first and then issue `UPDATE`(that doesn't seem right).

**Comment by za-arthur** [comment]
> Yes, there is but new installation defaults to 1.6. This means we need an installation script for it. The other way is to install 1.5 first and then issue UPDATE(that doesn't seem right).

Postgres can execute necessary scripts up to version 1.6. You don't need to install 1.5 first and then update to 1.6.

**Comment by za-arthur** [comment]
https://github.com/postgres/postgres/tree/master/contrib/pg_trgm

**Comment by za-arthur** [comment]
> Sample error:

But AFAIK older Postgres versions cannot execute upgrade scripts, indeed.

**Review by za-arthur — APPROVED** [review]

**Comment by za-arthur** [comment]
> ERROR:  extension "pgtelemetry" has no installation script nor update path for version "1.6"

What servers is this?

**Comment by bolajiwahab** [comment]
> > Yes, there is but new installation defaults to 1.6. This means we need an installation script for it. The other way is to install 1.5 first and then issue UPDATE(that doesn't seem right).
> 
> Postgres can execute necessary scripts up to version 1.6. You don't need to install 1.5 first and then update to 1.6.

Okay but I got this error so something is not right
```
CREATE EXTENSION pgtelemetry;
ERROR:  extension "pgtelemetry" has no installation script nor update path for version "1.6"
```
Can you try it at your end(a fresh installation)?

**Comment by bolajiwahab** [comment]
> > ERROR:  extension "pgtelemetry" has no installation script nor update path for version "1.6"
> 
> What servers is this?

14.3

**Comment by bolajiwahab** [comment]
> > Yes, there is but new installation defaults to 1.6. This means we need an installation script for it. The other way is to install 1.5 first and then issue UPDATE(that doesn't seem right).
> 
> Postgres can execute necessary scripts up to version 1.6. You don't need to install 1.5 first and then update to 1.6.

Okay, I guess you are right. There was a bug indeed in the update path. I wonder how we missed it.

Notice the name  `pgtelemetry--1.5.sql--1.6.sql` in https://github.com/adjust/pg-telemetry/blob/master/extension/pgtelemetry--1.5.sql--1.6.sql

**Comment by bolajiwahab** [comment]
> > Sample error:
> 
> But AFAIK older Postgres versions cannot execute upgrade scripts, indeed.

If this is true, then shall we also supply the installation script?

**Comment by za-arthur** [comment]
AFAIK Postgres can follow update path  since Postgres 10. For older versions it makes sense to have installation script.

> Notice the name pgtelemetry--1.5.sql--1.6.sql in https://github.com/adjust/pg-telemetry/blob/master/extension/pgtelemetry--1.5.sql--1.6.sql

Can you fix it as well?

**Comment by bolajiwahab** [comment]
> Can you fix it as well?

Fixed by [39c02e5](https://github.com/adjust/pg-telemetry/pull/27/commits/39c02e57275f228827cf6c893ffa6c38b9f3c1e8)

**Review by za-arthur — APPROVED** [review]

**Comment by za-arthur** [comment]
> Fixed by [39c02e5](https://github.com/adjust/pg-telemetry/pull/27/commits/39c02e57275f228827cf6c893ffa6c38b9f3c1e8)

Thanks!

**Pull request merged**
